<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="UserGrid.aspx.cs" Inherits="EMSASP.UserGrid" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<title></title>
<style type="text/css">
.style1
{
width: 614px;
}
.style3
{
color: #FF0000;
font-size: xx-large;
}
.style4
{
color: #006600;
font-size: xx-large;
}
.style7
{
}
.style11
{
width: 360px;
}
.style12
{
font-weight: bold;
text-align: right;
width: 69px;
}
.style13
{
width: 69px;
}
</style>
</head>
<body>
<form id="form1" runat="server">
<div>
 
<table  align="center" class="style1" style="border: thin solid #008080">
<tr>
<td
 
style="border-bottom-style: solid; border-bottom-width: thin; border-bottom-color: #008080"
class="style3">
<strong>&nbsp; Edit / Update / Delete USER DETAILS</strong></td>
</tr>
<tr>
<td
style="border-bottom: thin solid #008080; text-align: center;"
class="style4">
&nbsp;</td>
</tr>
<tr>
<td class="style7">
<table align="center" class="style11">
<tr>
<td class="style12">
&nbsp;</td>
<td>
&nbsp;</td>
</tr>
<tr>
<td class="style12">
Name :</td>
<td>
<asp:TextBox ID="txtname" runat="server"></asp:TextBox>
</td>
</tr>
<tr>
<td class="style12">
Gender :</td>
<td>
<asp:TextBox ID="txtgender" runat="server"></asp:TextBox>
</td>
</tr>
<tr>
<td class="style12">
Mobile :</td>
<td>
<asp:TextBox ID="txtmobile" runat="server"></asp:TextBox>
</td>
</tr>
<tr>
<td class="style12">
Email :</td>
<td>
<asp:TextBox ID="Textemail" runat="server"></asp:TextBox>
</td>
</tr>
<tr>
<td class="style12">
User type :</td>
<td>
<asp:TextBox ID="txtutype" runat="server"></asp:TextBox>
</td>
</tr>
<tr>
<td class="style12">
Username :</td>
<td>
<asp:TextBox ID="txtuname" runat="server"></asp:TextBox>
</td>
</tr>
<tr>
<td class="style12">
Password :</td>
<td>
<asp:TextBox ID="txtpass" runat="server"></asp:TextBox>
</td>
</tr>
<tr>
<td class="style13">
&nbsp;</td>
<td>
<asp:Button ID="btnsave" runat="server" Text="SAVE" onclick="btnsave_Click"
style="font-weight: 700" />
</td>
</tr>
<tr>
<td class="style13">
&nbsp;</td>
<td>
&nbsp;</td>
</tr>
<tr>
<td class="style13">
&nbsp;</td>
<td>
    
<asp:GridView ID="GridView1" runat="server" BackColor="White"
BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3"
style="text-align: center" Width="284px" AutoGenerateDeleteButton="True"
AutoGenerateEditButton="True" DataKeyNames="user_id"
onrowcancelingedit="GridView1_RowCancelingEdit"
onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing"
onrowupdating="GridView1_RowUpdating" AutoGenerateColumns="False" >
   
    <Columns>
        <asp:BoundField DataField="user_id" HeaderText="user_id" InsertVisible="False" ReadOnly="True" SortExpression="user_id" />
        <asp:BoundField DataField="user_name" HeaderText="user_name" SortExpression="user_name" />
        <asp:BoundField DataField="gender" HeaderText="gender" SortExpression="gender" />
        <asp:BoundField DataField="mobile" HeaderText="mobile" SortExpression="mobile" />
        <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
        <asp:BoundField DataField="user_type" HeaderText="user_type" SortExpression="user_type" />
        <asp:BoundField DataField="user_login_name" HeaderText="user_login_name" SortExpression="user_login_name" />
        <asp:BoundField DataField="user_login_password" HeaderText="user_login_password" SortExpression="user_login_password" />
    </Columns>
   
<FooterStyle BackColor="White" ForeColor="#000066" />
<HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
<PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
<RowStyle ForeColor="#000066" />
<SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
<SortedAscendingCellStyle BackColor="#F1F1F1" />
<SortedAscendingHeaderStyle BackColor="#007DBB" />
<SortedDescendingCellStyle BackColor="#CAC9C9" />
<SortedDescendingHeaderStyle BackColor="#00547E" />
</asp:GridView>
</td>
</tr>
</table>
</td>
</tr>
</table>
 
</div>
</form>
</body>
</html>
